[env:lilygo_t_sim7000g]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 115200
upload_port = /dev/cu.usbserial-59680313751
monitor_port = /dev/cu.usbserial-59680313751
lib_deps =
  vshymanskyy/TinyGSM@^0.12.0
  bblanchon/ArduinoJson@^7.3.1
build_flags =
  -D TINY_GSM_MODEM_SIM7000SSL
  -D TINY_GSM_RX_BUFFER=1024
